version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build: ./client/job_tracker
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
